# Generated by Django 3.1.1 on 2020-10-20 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teaminfo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hackteam',
            old_name='display_name',
            new_name='Participants_name',
        ),
    ]
