# Generated by Django 3.1.1 on 2020-10-20 09:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teaminfo', '0002_auto_20201020_0925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hackteam',
            name='Participants_name',
        ),
        migrations.AddField(
            model_name='hackteam',
            name='participants',
            field=models.ManyToManyField(related_name='team_participants', to=settings.AUTH_USER_MODEL),
        ),
    ]
